apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: viewer-binding
subjects:
  - kind: User
    name: user_viewer
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: viewer-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: editor-binding
subjects:
  - kind: User
    name: user_editor
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: editor-role
  apiGroup: rbac.authorization.k8s.io